export const BeersTypes = {
  GET_BEERS: 'GET_BEERS',
  GET_MORE_BEERS: 'GET_MORE_BEERS',
  FILTER_BEERS: 'FILTER_BEERS',
  SET_FILTERED_BEERS: 'SET_FILTERED_BEERS',
  BEERS_RESPONSE: 'GET_BEERS_RESPONSE',
}
